### ISSUE TITLE
ContactUs Integration

### ISSUE THREAD

**Issue by KevinWhite** [FutureNorthants/VirtualWorker#47]
equirements

BOT to search Contact Us form for location in a new step by step process. See 'Process'
BOT to use the service area drop down provided on Contact Us form by the customer to determine service area.
Look up list for service area - WNC and NNC to go through look up list and advise if BOT should use lex service
New template for Forward to Sovereign
New template for Misdirected queries
Improvement required to the way that the BOT extracts the information from Contact Us to make it more accurate. See 'How it Extracts'

Customer Requirement

As a customer i want my enquiry to be forwarded from the website to the correct relevant sovereign authority, to be determined by service area and location provided.

User Acceptance

The customer will access the Contact Us on either the West or North website and the following process will occur. We will use North as an example but the same process should occur for West (switch North wording for West):

Process

Customer completes form
Bot reads Text Field
If location is identified from the Text Field
and is determined as North, send query to appropriate North sovereign using Improved Forward to Sov template
or is determined as West (out of area) BOT to forward to West sovereign and email customer the Misdirected Template
or is determined as out of area (not Northamptonshire) BOT to use Home address to determine location as listed below
If location is not identified from the Text Field then BOT to use Home address for location
If home address is North forward to North sovereign using Improved Forward to Sov template
If home address is out of area (West) BOT to forward to west sovereign and email customer the Misdirected Template **
If home address is out of area (not Northamptonshire) BOT to send Location Required email to customer and Case would go into Hub - Awaiting Location Confirmation. NOTE - for North there is a bug for this and it does not send the Location Required email to the customer, temp fix put in place so that the Case is put into Hub - Awaiting Review however that too is not working as per ENC Hub.
** POSSIBLE FUTURE ENHANCEMENT - What if a customer completes a North form, no address in Text Field, home address is a West address – fair assumption that if they completed a North form that the request would be about the North area. Should these go to Awaiting Location Conf and send the customer a Location Request email? We will go live with what we have above and then review and see if it causes any issues.

How the BOT will Extact Information
All information below will moved to their own fields instead of going in as one to be read by the BOT. Norbert currently reads entirety of email to ascertain location and service. By separating this, Norbert will be able to analyse the location and service area more effectively.

Form data:

Service: Waste and recycling
Enquiry details: I run a business in Billing and we have not had our business waste collected for 2 weeks now.
First name: Megan
Last name: McTesty
Email address: meganlouisecrowthers16@gmail.com
Telephone number: 07387581485
Address line 1: ORIENTAL PARADISE RESTAURANT, THE CAUSEWAY
Address line 2: NORTHAMPTON
Postcode: NN3 9EX

**Comment by MeganCrowthers** [comment]
### ContactUs Form on West Website:
All other information below will moved to their own fields instead of going in as one. Norbert currently reads entirety of email to ascertain location and service. By separating this, Norbert will be able to analyse the location and service area more effectively. 

**Form data:**

- Service: Waste and recycling
- Enquiry details: I run a business in Billing and we have not had our business waste collected for 2 weeks now. 
- First name: Megan
- Last name: McTesty
- Email address: meganlouisecrowthers16@gmail.com
- Telephone number: 07387581485
- Address line 1: ORIENTAL PARADISE RESTAURANT, THE CAUSEWAY
- Address line 2: NORTHAMPTON
- Postcode: NN3 9EX



1.	If home address is not within the enquiry details - Norbert will get the get home address as outlined on the form field.  If it can’t find address in text and form – Norbert will ask for location
2.	A New template will be required to hold these fields

Look up list on service area - WNC and NNC to go through look up list and advise if should list to lex service

**Comment by MeganCrowthers** [comment]
This has completed in previous sprints - case closed
