### ISSUE TITLE
Contact Us - Manual address entry not parsed by bot; local request is sent out

### ISSUE THREAD

**Issue by AndyBoatwright** [FutureNorthants/VirtualWorker#60]
If the customer uses the manual address entry option on the CUs form, when Norby receives the case, it doesn't detect or verify the address, it just automatically issues a loc req email.

UPDATE - to parse address from the manual entry fields to prevent having to issue loc req.

Longevity of this issue depends on API integration; probably not required when that is undertaken.

**Comment by KevinWhite** [comment]
![image](https://user-images.githubusercontent.com/960938/117983334-c0d53d80-b32e-11eb-9311-5ce89fafd3ba.png)

**Comment by MeganCrowthers** [comment]
Tested under EMA003001 no postcode given - put into outputs sent to right department 

Tested under EMA003002 no postcode given - put into outputs didn't sent to right department however this is because bot does not understand areas yet

Tested under EMA003003 no postcode given - put into outputs - request further info as unable to location - send back nonsense - bot put into unitary awaiting review 

Tested under EMA003004 no postcode given - put in Daventry town - it was recognised - bot send to Dav

**Comment by MeganCrowthers** [comment]
Confirmed by NNC that they have done some tests and this is now ready to go live. @KevinWhite please can you put this live :)

**Comment by lfayter** [comment]
Tested in live environment (NNC):-  
EMN002375 - no postcode given.  ALC email received, replied to email providing address.  Correct service area and council allocated, email response received.   Case went to 'Closed'.  
EMN002376 - postcode provided.  Email response received.  Correct service area and council allocated.  Case went to 'Closed'.
